### ISSUE TITLE
Increase font size of sentence in /clients route

### ISSUE THREAD

**Issue by Binco97** [Software-Engineering-2021-P9/solidarity-purchasing-group-P09#32]
please, increase the font size of the sentence that appears in the Manage clients view in route `/employee/clients/`

> "Search for a registered client using the form above.
> Clients can be retrieved using one between: email, name, address and phone number."

**Comment by MarcoBramini** [comment]
Already managed here: https://github.com/Software-Engineering-2021-P9/solidarity-purchasing-group-P09/issues/28
